version: '3'
services:
  mysqldb:
    image: mysql:latest
    ports:
      - '3306:3306'
    volumes:
      - ./src/test/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass